name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download badge image
      run: |
        curl -L -o ./assets/badge.png "https://tryhackme-badges.s3.amazonaws.com/NotYousefNein.png"
    
    - name: Commit and push the badge image
      run: |
        git add ./assets/badge.png
        git commit -m "Add new badge image"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
