name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Allow GitHub Actions to push changes

jobs:
  tryhackme-badge-update:
    name: Update this repo's TryHackMe badge with the latest image badge
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download badge image
      run: |
        curl -L -o badge.png "https://tryhackme-badges.s3.amazonaws.com/NotYousefNein.png"
    
    - name: Configure git identity
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
    
    - name: Commit and push the badge image
      run: |
        ls
        git pull
        git add .
        git status
        git commit -m "Add new badge image"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
